replicaCount: 1

image:
  pullPolicy: IfNotPresent
  community:
    tag: "1.86.0"

enterprise:
  enabled: false

useDevPostgres: false

existingSecret: lakefs-secrets
secretKeys:
  databaseConnectionString: database_connection_string
  authEncryptSecretKey: auth_encrypt_secret_key

service:
  type: ClusterIP
  port: 80

deployment:
  port: 8000

nodeSelector:
  ml-platform.local/workload-class: platform

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

extraEnvVars:
  - name: LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: data-storage-scoped-credentials
        key: artifacts-access-key-id
  - name: LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: data-storage-scoped-credentials
        key: artifacts-secret-access-key

lakefsConfig: |
  logging:
    format: text
    level: INFO
    output: "-"
  database:
    type: postgres
  blockstore:
    type: s3
    s3:
      region: garage
      endpoint: http://garage-s3.ml-platform-data.svc.cluster.local:3900
      force_path_style: true
      discover_bucket_region: false
      disable_pre_signed: true
      disable_pre_signed_ui: true
