updateStrategy:
  type: Recreate

expose:
  type: clusterIP
  tls:
    enabled: false
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443

externalURL: http://127.0.0.1:15000

existingSecretAdminPassword: harbor-admin

secretKey: "study-registry01"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 1Gi
    jobservice:
      jobLog:
        size: 1Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
    trivy:
      size: 1Gi
  imageChartStorage:
    type: filesystem
    filesystem:
      rootdirectory: /storage

nginx:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 75m
      memory: 128Mi

portal:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 75m
      memory: 128Mi

core:
  secret: "study-core-key01"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

jobservice:
  secret: "study-job-key001"
  maxJobWorkers: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

registry:
  secret: "study-reg-key001"
  registry:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
  controller:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 75m
        memory: 128Mi
  relativeurls: true

trivy:
  enabled: false

database:
  type: internal
  internal:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    initContainer:
      migrator:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
      permissions:
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 75m
            memory: 128Mi

redis:
  type: internal
  internal:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

exporter:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 75m
      memory: 128Mi
