apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - layout-configmap.yaml
  - retention-configmap.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: ml-platform-study
      app.kubernetes.io/managed-by: kustomize
      ml-platform.local/lifecycle: study
      ml-platform.local/environment: dev
      ml-platform.local/cluster-route: kind
    includeSelectors: false
