apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: housing-database-credential
  namespace: ml-platform-project-housing
  labels:
    app.kubernetes.io/name: housing-database-credential
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-housing
    kind: SecretStore
  target:
    name: housing-database-credential
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: ml-platform-study
          ml-platform.local/source: openbao
  data:
    - secretKey: username
      remoteRef:
        key: projects/housing/database/study-reader
        property: username
    - secretKey: password
      remoteRef:
        key: projects/housing/database/study-reader
        property: password
    - secretKey: database
      remoteRef:
        key: projects/housing/database/study-reader
        property: database
