apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-store.yaml
  - external-secret.yaml
  - unauthorized-service-account.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ml-platform-study
      ml-platform.local/phase: "02"
      ml-platform.local/component: secrets
      ml-platform.local/cluster-route: kind
