apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-housing
  namespace: ml-platform-project-housing
  labels:
    app.kubernetes.io/name: openbao-housing
    app.kubernetes.io/component: secrets
spec:
  provider:
    vault:
      server: http://openbao.ml-platform-system.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: openbao-housing-reader-token
          key: token
