apiVersion: v1
kind: ServiceAccount
metadata:
  name: unauthorized-secret-reader
  namespace: ml-platform-project-housing
  labels:
    app.kubernetes.io/name: unauthorized-secret-reader
    app.kubernetes.io/component: secrets-test
