apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      ml-platform.local/environment: dev
      ml-platform.local/cluster-route: kind
    includeSelectors: false

