apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gateway
  - issuers.yaml
  - certificates.yaml
  - http-redirect-route.yaml
patches:
  - path: gateway-https-listener-patch.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: ml-platform-local
      namespace: ml-platform-system
  - path: gateway-echo-https-parent-patch.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: gateway-echo
      namespace: ml-platform-project-housing
labels:
  - pairs:
      ml-platform.local/tls-profile: local-ca
    includeSelectors: false
