apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-housing-rbac.yaml
  - platform-observer-rbac.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ml-platform-study
      ml-platform.local/phase: "02"
      ml-platform.local/component: rbac
